apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-admin-app-deploy
  namespace: front-admin
  labels:
    app: front-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-admin
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: front-admin
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: front-admin
      containers:
        - name: front-admin-app-container
          image: ghcr.io/cdsl-research/front-admin:master-2b81d22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_PAPER_HOST
              value: paper-app.paper
            - name: SERVICE_PAPER_PORT
              value: "4000"
            - name: SERVICE_AUTHOR_HOST
              value: author-app.author
            - name: SERVICE_AUTHOR_PORT
              value: "4000"
            - name: SERVICE_THUMBNAIL_HOST
              value: thumbnail-app.thumbnail
            - name: SERVICE_THUMBNAIL_PORT
              value: "4000"
            - name: SERVICE_FULLTEXT_HOST
              value: fulltext-app.fulltext
            - name: SERVICE_FULLTEXT_PORT
              value: "4000"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(POD_NAMESPACE),k8s.node.name=$(NODE_NAME)"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              # value: "http://192.168.201.12:4317"
              value: "http://signoz-k8s-k8s-infra-otel-agent.signoz.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "front-admin"
---
apiVersion: v1
kind: Service
metadata:
  name: front-admin-app
  namespace: front-admin
spec:
  type: NodePort
  selector:
    app: front-admin
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
      nodePort: 30100
