apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-admin-app-deploy
  namespace: front-admin
  labels:
    app: front-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-admin
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
      labels:
        app: front-admin
    spec:
      containers:
        - name: front-admin-app-container
          image: ghcr.io/cdsl-research/front-admin:master-d03e42d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_PAPER_HOST
              value: paper-app.paper
            - name: SERVICE_PAPER_PORT
              value: "4000"
            - name: SERVICE_AUTHOR_HOST
              value: author-app.author
            - name: SERVICE_AUTHOR_PORT
              value: "4000"
            - name: SERVICE_THUMBNAIL_HOST
              value: thumbnail-app.thumbnail
            - name: SERVICE_THUMBNAIL_PORT
              value: "4000"
            - name: SERVICE_FULLTEXT_HOST
              value: fulltext-app.fulltext
            - name: SERVICE_FULLTEXT_PORT
              value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: front-admin-app
  namespace: front-admin
spec:
  type: NodePort
  selector:
    app: front-admin
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
      nodePort: 30100
