apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-minio-deploy
  namespace: paper
  labels:
    minio: paper
spec:
  replicas: 1
  selector:
    matchLabels:
      minio: paper
  template:
    metadata:
      labels:
        minio: paper
    spec:
      containers:
        - name: paper-minio-container
          image: minio/minio:RELEASE.2021-09-03T03-56-13Z
          imagePullPolicy: IfNotPresent
          command: ["server"]
          args: ["/data", "--console-address", ":9100"]
          ports:
            - name: minio api
              containerPort: 9000
            - name: minio dashboard
              containerPort: 9100
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
          volumeMounts:
            - name: paper-minio-volv
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - ls
                - /data/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 4
      volumes:
        - name: paper-minio-volv
          persistentVolumeClaim:
            claimName: paper-minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-minio-pvc
  namespace: paper
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: paper-minio
spec:
  type: ClusterIP
  selector:
    minio: paper
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: paper-minio-dashboard
  namespace: paper
spec:
  type: NodePort
  selector:
    minio: paper
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100