apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-mongo-express-deploy
  namespace: paper
  labels:
    mongo-express: paper
spec:
  replicas: 1
  selector:
    matchLabels:
      mongo-express: paper
  template:
    metadata:
      labels:
        mongo-express: paper
    spec:
      containers:
        - name: paper-mongo-express-container
          image: mongo-express:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: example
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://root:example@paper-mongo.paper:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: paper-mongo-express
  namespace: paper
spec:
  type: NodePort
  selector:
    mongo-express: paper
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
