apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-app-deploy
  namespace: stats
  labels:
    app: stats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: stats
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: stats
      containers:
        - name: stats-app-container
          image: ghcr.io/cdsl-research/stats:master-aac9010
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: stats-mongo.stats
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://192.168.201.12:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "stats"
---
apiVersion: v1
kind: Service
metadata:
  name: stats-app
  namespace: stats
spec:
  type: NodePort
  selector:
    app: stats
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
