apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-deployment
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: paper-container
          image: hello-world
          ports:
            - containerPort: 8000
