version: "3.9"
services:
  fulltext-app:
    build: .
    command: [ "main:app", "--reload", "--host", "0.0.0.0" ]
    restart: always
    volumes:
      - .:/work
    ports:
      - "4500:8000"
    environment:
      - ELASTIC_PASSWORD=elastic123
    networks:
      - frontend
  fulltext-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 4503:9200
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
  fulltext-kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 4504:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://fulltext-elasticsearch:9200
    depends_on:
      - fulltext-app

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local

networks:
  frontend:
    external: true
