version: "3.3"
services:
  author-app:
    build: .
    command: ["main:app", "--reload", "--host", "0.0.0.0"]
    restart: always
    volumes:
      - .:/work
    ports:
      - "4200:8000"
    environment:
      - MONGO_HOST=author-mongo
    depends_on:
      - author-mongo
    networks:
      - frontend
      - backend
  author-mongo:
    image: mongo:5.0
    restart: always
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
  author-mongo-seed:
    image: mongo:5.0
    depends_on:
      - author-mongo
    volumes:
      - ./mongo_init_d:/dump:ro
    command: ["/bin/bash", "/dump/setup.sh"]
    networks:
      - backend
  author-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4201:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@author-mongo:27017/
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend: