apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-mongo-express-deploy
  namespace: author
  labels:
    mongo-express: author
spec:
  replicas: 1
  selector:
    matchLabels:
      mongo-express: author
  template:
    metadata:
      labels:
        mongo-express: author
    spec:
      containers:
        - name: author-mongo-express-container
          image: mongo-express:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_SERVER
              value: author-mongo.author
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: author-mongo-secret
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: author-mongo-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: author-mongo-express
  namespace: author
spec:
  type: NodePort
  selector:
    mongo-express: author
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
