apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-app-deploy
  namespace: author
  labels:
    app: author
spec:
  replicas: 3
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: author
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: author  # REPLACE_TAG for author-app
      containers:
        - name: author-app-container
          image: ghcr.io/cdsl-research/author:master-b812ad3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: author-mongo.author
---
apiVersion: v1
kind: Service
metadata:
  name: author-app
  namespace: author
spec:
  type: NodePort
  selector:
    app: author
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
