apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-app-deploy
  namespace: author
  labels:
    app: author
spec:
  replicas: 3
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        app: author
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: author  # REPLACE_TAG for author-app
      containers:
        - name: author-app-container
          image: ghcr.io/cdsl-research/author:master-2b81d22
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: author-mongo.author
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(POD_NAMESPACE),k8s.node.name=$(NODE_NAME)"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              # value: "http://192.168.201.12:4317"
              value: "http://signoz-k8s-k8s-infra-otel-agent.signoz.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: "author"
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - clematis-worker2
---
apiVersion: v1
kind: Service
metadata:
  name: author-app
  namespace: author
spec:
  type: NodePort
  selector:
    app: author
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
