apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-app-deploy
  namespace: author
  labels:
    app: author
spec:
  replicas: 3
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      annotations:
        sidecar.istio.io/status: ""
      labels:
        app: author
    spec:
      containers:
        - name: author-app-container
          image: ghcr.io/cdsl-research/author:master-a5a5424
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_HOST
              value: author-mongo.author
---
apiVersion: v1
kind: Service
metadata:
  name: author-app
  namespace: author
spec:
  type: NodePort
  selector:
    app: author
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000
