apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-mongo-express-deploy
  namespace: author
  labels:
    mongo-express: author
spec:
  replicas: 1
  selector:
    matchLabels:
      mongo-express: author
  template:
    metadata:
      labels:
        mongo-express: author
    spec:
      containers:
        - name: author-mongo-express-container
          image: mongo-express:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: example
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://root:example@author-mongo.author:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: author-mongo-express
  namespace: author
spec:
  type: NodePort
  selector:
    mongo-express: author
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
