apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulltext-kibana-deploy
  namespace: fulltext
  labels:
    kibana: fulltext
spec:
  replicas: 1
  selector:
    matchLabels:
      kibana: fulltext
  template:
    metadata:
      labels:
        kibana: fulltext
    spec:
      containers:
        - name: fulltext-kibana-container
          image: docker.elastic.co/kibana/kibana:8.1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://fulltext-elastic.fulltext:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: fulltext-kibana
  namespace: fulltext
spec:
  type: NodePort
  selector:
    db: fulltext
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
