"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_paper_handler_paper_post(self):
        """Test case for create_paper_handler_paper_post

        Create Paper Handler  # noqa: E501
        """
        pass

    def test_download_paper_handler_paper_paper_uuid_download_get(self):
        """Test case for download_paper_handler_paper_paper_uuid_download_get

        Download Paper Handler  # noqa: E501
        """
        pass

    def test_healthz_handler_healthz_get(self):
        """Test case for healthz_handler_healthz_get

        Healthz Handler  # noqa: E501
        """
        pass

    def test_read_paper_handler_paper_paper_uuid_get(self):
        """Test case for read_paper_handler_paper_paper_uuid_get

        Read Paper Handler  # noqa: E501
        """
        pass

    def test_read_papers_handler_paper_get(self):
        """Test case for read_papers_handler_paper_get

        Read Papers Handler  # noqa: E501
        """
        pass

    def test_root_handler_get(self):
        """Test case for root_handler_get

        Root Handler  # noqa: E501
        """
        pass

    def test_topz_handler_topz_get(self):
        """Test case for topz_handler_topz_get

        Topz Handler  # noqa: E501
        """
        pass

    def test_update_paper_handler_paper_paper_uuid_put(self):
        """Test case for update_paper_handler_paper_paper_uuid_put

        Update Paper Handler  # noqa: E501
        """
        pass

    def test_upload_paper_file_handler_paper_paper_uuid_upload_post(self):
        """Test case for upload_paper_file_handler_paper_paper_uuid_upload_post

        Upload Paper File Handler  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
