version: "3.9"
services:
  app:
    build: .
    command: ["main:app", "--reload", "--host", "0.0.0.0"]
    restart: always
    volumes:
      - .:/work
    ports:
      - "4100:8000"
  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - ./mongo_init_d:/docker-entrypoint-initdb.d:ro
    # ports:
    #   - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4101:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/