name: Build container images
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    if: ${{ github.event.pusher.email != 'k8s-config-updater@tak-cslab.org' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: ["author", "front-admin", "front", "paper"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag for master
        run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          CUR_BRANCH=$(git symbolic-ref --short HEAD)
          echo "DOCKER_TAG=${CUR_BRANCH}-${COMMITID}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.target }}
          push: true
          tags: ghcr.io/cdsl-research/${{ matrix.target }}:${{ env.DOCKER_TAG }}

      - run: |
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          find deploy -type f -exec sed -i "s/:master-.*/:master-$COMMITID/g" \{\} \;
          git config --local user.email "k8s-config-updater@tak-cslab.org"
          git config --local user.name "github-actions"
          git add deploy/
          git commit -m 'Auto commit by k8s-config updater'
          git push origin HEAD