name: KubeLinter
on:
  push:
    branches:
      - master
jobs:
  kubelint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Scan repo with kube-linter
        uses: stackrox/kube-linter-action@v1.0.2
        with:
          directory: deploy/
          config: .kube-linter/config.yaml